# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gripper_ntlab_msgs/CartesianPosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CartesianPosition(genpy.Message):
  _md5sum = "0f9f2aa44155913dda5f4deaeec35ddd"
  _type = "gripper_ntlab_msgs/CartesianPosition"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x1
float64 y1
float64 x2
float64 y2
float64 rad
uint8 buffer
bool torque"""
  __slots__ = ['x1','y1','x2','y2','rad','buffer','torque']
  _slot_types = ['float64','float64','float64','float64','float64','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x1,y1,x2,y2,rad,buffer,torque

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CartesianPosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x1 is None:
        self.x1 = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.x2 is None:
        self.x2 = 0.
      if self.y2 is None:
        self.y2 = 0.
      if self.rad is None:
        self.rad = 0.
      if self.buffer is None:
        self.buffer = 0
      if self.torque is None:
        self.torque = False
    else:
      self.x1 = 0.
      self.y1 = 0.
      self.x2 = 0.
      self.y2 = 0.
      self.rad = 0.
      self.buffer = 0
      self.torque = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d2B().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.rad, _x.buffer, _x.torque))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 42
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.rad, _x.buffer, _x.torque,) = _get_struct_5d2B().unpack(str[start:end])
      self.torque = bool(self.torque)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d2B().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.rad, _x.buffer, _x.torque))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 42
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.rad, _x.buffer, _x.torque,) = _get_struct_5d2B().unpack(str[start:end])
      self.torque = bool(self.torque)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d2B = None
def _get_struct_5d2B():
    global _struct_5d2B
    if _struct_5d2B is None:
        _struct_5d2B = struct.Struct("<5d2B")
    return _struct_5d2B
