; Auto-generated. Do not edit!


(cl:in-package denso_cobotta_gripper-msg)


;//! \htmlinclude GripperMoveResult.msg.html

(cl:defclass <GripperMoveResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GripperMoveResult (<GripperMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_cobotta_gripper-msg:<GripperMoveResult> is deprecated: use denso_cobotta_gripper-msg:GripperMoveResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GripperMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:success-val is deprecated.  Use denso_cobotta_gripper-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperMoveResult>) ostream)
  "Serializes a message object of type '<GripperMoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperMoveResult>) istream)
  "Deserializes a message object of type '<GripperMoveResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperMoveResult>)))
  "Returns string type for a message object of type '<GripperMoveResult>"
  "denso_cobotta_gripper/GripperMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperMoveResult)))
  "Returns string type for a message object of type 'GripperMoveResult"
  "denso_cobotta_gripper/GripperMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperMoveResult>)))
  "Returns md5sum for a message object of type '<GripperMoveResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperMoveResult)))
  "Returns md5sum for a message object of type 'GripperMoveResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperMoveResult>)))
  "Returns full string definition for message of type '<GripperMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool     success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperMoveResult)))
  "Returns full string definition for message of type 'GripperMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool     success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperMoveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperMoveResult
    (cl:cons ':success (success msg))
))
