; Auto-generated. Do not edit!


(cl:in-package denso_cobotta_gripper-msg)


;//! \htmlinclude VacuumMoveGoal.msg.html

(cl:defclass <VacuumMoveGoal> (roslisp-msg-protocol:ros-message)
  ((direction
    :reader direction
    :initarg :direction
    :type cl:integer
    :initform 0)
   (power_percentage
    :reader power_percentage
    :initarg :power_percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass VacuumMoveGoal (<VacuumMoveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VacuumMoveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VacuumMoveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_cobotta_gripper-msg:<VacuumMoveGoal> is deprecated: use denso_cobotta_gripper-msg:VacuumMoveGoal instead.")))

(cl:ensure-generic-function 'direction-val :lambda-list '(m))
(cl:defmethod direction-val ((m <VacuumMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:direction-val is deprecated.  Use denso_cobotta_gripper-msg:direction instead.")
  (direction m))

(cl:ensure-generic-function 'power_percentage-val :lambda-list '(m))
(cl:defmethod power_percentage-val ((m <VacuumMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:power_percentage-val is deprecated.  Use denso_cobotta_gripper-msg:power_percentage instead.")
  (power_percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VacuumMoveGoal>) ostream)
  "Serializes a message object of type '<VacuumMoveGoal>"
  (cl:let* ((signed (cl:slot-value msg 'direction)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'power_percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VacuumMoveGoal>) istream)
  "Deserializes a message object of type '<VacuumMoveGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'direction) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'power_percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VacuumMoveGoal>)))
  "Returns string type for a message object of type '<VacuumMoveGoal>"
  "denso_cobotta_gripper/VacuumMoveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VacuumMoveGoal)))
  "Returns string type for a message object of type 'VacuumMoveGoal"
  "denso_cobotta_gripper/VacuumMoveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VacuumMoveGoal>)))
  "Returns md5sum for a message object of type '<VacuumMoveGoal>"
  "44fa814773c8fc7eca6878dd64e3fabc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VacuumMoveGoal)))
  "Returns md5sum for a message object of type 'VacuumMoveGoal"
  "44fa814773c8fc7eca6878dd64e3fabc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VacuumMoveGoal>)))
  "Returns full string definition for message of type '<VacuumMoveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 direction~%float64 power_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VacuumMoveGoal)))
  "Returns full string definition for message of type 'VacuumMoveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 direction~%float64 power_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VacuumMoveGoal>))
  (cl:+ 0
     4
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VacuumMoveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'VacuumMoveGoal
    (cl:cons ':direction (direction msg))
    (cl:cons ':power_percentage (power_percentage msg))
))
