; Auto-generated. Do not edit!


(cl:in-package denso_cobotta_gripper-msg)


;//! \htmlinclude VacuumMoveResult.msg.html

(cl:defclass <VacuumMoveResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass VacuumMoveResult (<VacuumMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VacuumMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VacuumMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_cobotta_gripper-msg:<VacuumMoveResult> is deprecated: use denso_cobotta_gripper-msg:VacuumMoveResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <VacuumMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:success-val is deprecated.  Use denso_cobotta_gripper-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VacuumMoveResult>) ostream)
  "Serializes a message object of type '<VacuumMoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VacuumMoveResult>) istream)
  "Deserializes a message object of type '<VacuumMoveResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VacuumMoveResult>)))
  "Returns string type for a message object of type '<VacuumMoveResult>"
  "denso_cobotta_gripper/VacuumMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VacuumMoveResult)))
  "Returns string type for a message object of type 'VacuumMoveResult"
  "denso_cobotta_gripper/VacuumMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VacuumMoveResult>)))
  "Returns md5sum for a message object of type '<VacuumMoveResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VacuumMoveResult)))
  "Returns md5sum for a message object of type 'VacuumMoveResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VacuumMoveResult>)))
  "Returns full string definition for message of type '<VacuumMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VacuumMoveResult)))
  "Returns full string definition for message of type 'VacuumMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VacuumMoveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VacuumMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'VacuumMoveResult
    (cl:cons ':success (success msg))
))
