; Auto-generated. Do not edit!


(cl:in-package denso_cobotta_gripper-msg)


;//! \htmlinclude VacuumMoveFeedback.msg.html

(cl:defclass <VacuumMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((pressure
    :reader pressure
    :initarg :pressure
    :type cl:float
    :initform 0.0)
   (stalled
    :reader stalled
    :initarg :stalled
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass VacuumMoveFeedback (<VacuumMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VacuumMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VacuumMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_cobotta_gripper-msg:<VacuumMoveFeedback> is deprecated: use denso_cobotta_gripper-msg:VacuumMoveFeedback instead.")))

(cl:ensure-generic-function 'pressure-val :lambda-list '(m))
(cl:defmethod pressure-val ((m <VacuumMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:pressure-val is deprecated.  Use denso_cobotta_gripper-msg:pressure instead.")
  (pressure m))

(cl:ensure-generic-function 'stalled-val :lambda-list '(m))
(cl:defmethod stalled-val ((m <VacuumMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_cobotta_gripper-msg:stalled-val is deprecated.  Use denso_cobotta_gripper-msg:stalled instead.")
  (stalled m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VacuumMoveFeedback>) ostream)
  "Serializes a message object of type '<VacuumMoveFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'pressure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'stalled) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VacuumMoveFeedback>) istream)
  "Deserializes a message object of type '<VacuumMoveFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pressure) (roslisp-utils:decode-double-float-bits bits)))
    (cl:setf (cl:slot-value msg 'stalled) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VacuumMoveFeedback>)))
  "Returns string type for a message object of type '<VacuumMoveFeedback>"
  "denso_cobotta_gripper/VacuumMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VacuumMoveFeedback)))
  "Returns string type for a message object of type 'VacuumMoveFeedback"
  "denso_cobotta_gripper/VacuumMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VacuumMoveFeedback>)))
  "Returns md5sum for a message object of type '<VacuumMoveFeedback>"
  "794836023aebbbc75ac9fc72f83a8a28")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VacuumMoveFeedback)))
  "Returns md5sum for a message object of type 'VacuumMoveFeedback"
  "794836023aebbbc75ac9fc72f83a8a28")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VacuumMoveFeedback>)))
  "Returns full string definition for message of type '<VacuumMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 pressure  # Not implemented.~%bool stalled      # True iff the gripper is exerting max effort and not moving~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VacuumMoveFeedback)))
  "Returns full string definition for message of type 'VacuumMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 pressure  # Not implemented.~%bool stalled      # True iff the gripper is exerting max effort and not moving~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VacuumMoveFeedback>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VacuumMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'VacuumMoveFeedback
    (cl:cons ':pressure (pressure msg))
    (cl:cons ':stalled (stalled msg))
))
