// Generated by gencpp from file gripper_ntlab_msgs/JointPosition.msg
// DO NOT EDIT!


#ifndef GRIPPER_NTLAB_MSGS_MESSAGE_JOINTPOSITION_H
#define GRIPPER_NTLAB_MSGS_MESSAGE_JOINTPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_ntlab_msgs
{
template <class ContainerAllocator>
struct JointPosition_
{
  typedef JointPosition_<ContainerAllocator> Type;

  JointPosition_()
    : position()
    , mode(0)  {
    }
  JointPosition_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> const> ConstPtr;

}; // struct JointPosition_

typedef ::gripper_ntlab_msgs::JointPosition_<std::allocator<void> > JointPosition;

typedef boost::shared_ptr< ::gripper_ntlab_msgs::JointPosition > JointPositionPtr;
typedef boost::shared_ptr< ::gripper_ntlab_msgs::JointPosition const> JointPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator1> & lhs, const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator1> & lhs, const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gripper_ntlab_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42665b9cfa738929ee7f26a4db0bd85b";
  }

  static const char* value(const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42665b9cfa738929ULL;
  static const uint64_t static_value2 = 0xee7f26a4db0bd85bULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_ntlab_msgs/JointPosition";
  }

  static const char* value(const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_ntlab_msgs::JointPosition_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_NTLAB_MSGS_MESSAGE_JOINTPOSITION_H
