// Generated by gencpp from file denso_cobotta_driver/ClearError.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_CLEARERROR_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_CLEARERROR_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/ClearErrorRequest.h>
#include <denso_cobotta_driver/ClearErrorResponse.h>


namespace denso_cobotta_driver
{

struct ClearError
{

typedef ClearErrorRequest Request;
typedef ClearErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearError
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::ClearError > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::denso_cobotta_driver::ClearError&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::ClearError > {
  static const char* value()
  {
    return "denso_cobotta_driver/ClearError";
  }

  static const char* value(const ::denso_cobotta_driver::ClearError&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::ClearErrorRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearError >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearErrorRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearError >
template<>
struct DataType< ::denso_cobotta_driver::ClearErrorRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::ClearErrorResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearError >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearErrorResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearError >
template<>
struct DataType< ::denso_cobotta_driver::ClearErrorResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_CLEARERROR_H
