// Generated by gencpp from file denso_cobotta_driver/ClearRobotError.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_CLEARROBOTERROR_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_CLEARROBOTERROR_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/ClearRobotErrorRequest.h>
#include <denso_cobotta_driver/ClearRobotErrorResponse.h>


namespace denso_cobotta_driver
{

struct ClearRobotError
{

typedef ClearRobotErrorRequest Request;
typedef ClearRobotErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearRobotError
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::ClearRobotError > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::denso_cobotta_driver::ClearRobotError&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::ClearRobotError > {
  static const char* value()
  {
    return "denso_cobotta_driver/ClearRobotError";
  }

  static const char* value(const ::denso_cobotta_driver::ClearRobotError&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::ClearRobotErrorRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearRobotError >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearRobotErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearRobotError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearRobotErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearRobotErrorRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearRobotError >
template<>
struct DataType< ::denso_cobotta_driver::ClearRobotErrorRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearRobotError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearRobotErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::ClearRobotErrorResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearRobotError >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearRobotErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearRobotError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearRobotErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearRobotErrorResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearRobotError >
template<>
struct DataType< ::denso_cobotta_driver::ClearRobotErrorResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearRobotError >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearRobotErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_CLEARROBOTERROR_H
