// Generated by gencpp from file denso_cobotta_driver/ClearSafeStateResponse.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATERESPONSE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct ClearSafeStateResponse_
{
  typedef ClearSafeStateResponse_<ContainerAllocator> Type;

  ClearSafeStateResponse_()
    : success(false)  {
    }
  ClearSafeStateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClearSafeStateResponse_

typedef ::denso_cobotta_driver::ClearSafeStateResponse_<std::allocator<void> > ClearSafeStateResponse;

typedef boost::shared_ptr< ::denso_cobotta_driver::ClearSafeStateResponse > ClearSafeStateResponsePtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::ClearSafeStateResponse const> ClearSafeStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/ClearSafeStateResponse";
  }

  static const char* value(const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearSafeStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::ClearSafeStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATERESPONSE_H
