// Generated by gencpp from file denso_cobotta_driver/ClearSafeState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/ClearSafeStateRequest.h>
#include <denso_cobotta_driver/ClearSafeStateResponse.h>


namespace denso_cobotta_driver
{

struct ClearSafeState
{

typedef ClearSafeStateRequest Request;
typedef ClearSafeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearSafeState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::ClearSafeState > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::denso_cobotta_driver::ClearSafeState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::ClearSafeState > {
  static const char* value()
  {
    return "denso_cobotta_driver/ClearSafeState";
  }

  static const char* value(const ::denso_cobotta_driver::ClearSafeState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::ClearSafeStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearSafeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearSafeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearSafeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearSafeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearSafeStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearSafeState >
template<>
struct DataType< ::denso_cobotta_driver::ClearSafeStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearSafeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearSafeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::ClearSafeStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ClearSafeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::ClearSafeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ClearSafeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearSafeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ClearSafeStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::ClearSafeState >
template<>
struct DataType< ::denso_cobotta_driver::ClearSafeStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ClearSafeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ClearSafeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_CLEARSAFESTATE_H
