// Generated by gencpp from file denso_cobotta_driver/ExecCalset.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_EXECCALSET_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_EXECCALSET_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/ExecCalsetRequest.h>
#include <denso_cobotta_driver/ExecCalsetResponse.h>


namespace denso_cobotta_driver
{

struct ExecCalset
{

typedef ExecCalsetRequest Request;
typedef ExecCalsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecCalset
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::ExecCalset > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::denso_cobotta_driver::ExecCalset&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::ExecCalset > {
  static const char* value()
  {
    return "denso_cobotta_driver/ExecCalset";
  }

  static const char* value(const ::denso_cobotta_driver::ExecCalset&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::ExecCalsetRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ExecCalset >
template<>
struct MD5Sum< ::denso_cobotta_driver::ExecCalsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ExecCalset >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ExecCalsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ExecCalsetRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::ExecCalset >
template<>
struct DataType< ::denso_cobotta_driver::ExecCalsetRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ExecCalset >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ExecCalsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::ExecCalsetResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::ExecCalset >
template<>
struct MD5Sum< ::denso_cobotta_driver::ExecCalsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::ExecCalset >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ExecCalsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::ExecCalsetResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::ExecCalset >
template<>
struct DataType< ::denso_cobotta_driver::ExecCalsetResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::ExecCalset >::value();
  }
  static const char* value(const ::denso_cobotta_driver::ExecCalsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_EXECCALSET_H
