// Generated by gencpp from file denso_cobotta_driver/GetBrakeStateRequest.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATEREQUEST_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct GetBrakeStateRequest_
{
  typedef GetBrakeStateRequest_<ContainerAllocator> Type;

  GetBrakeStateRequest_()
    {
    }
  GetBrakeStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBrakeStateRequest_

typedef ::denso_cobotta_driver::GetBrakeStateRequest_<std::allocator<void> > GetBrakeStateRequest;

typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateRequest > GetBrakeStateRequestPtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateRequest const> GetBrakeStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/GetBrakeStateRequest";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBrakeStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::denso_cobotta_driver::GetBrakeStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATEREQUEST_H
