// Generated by gencpp from file denso_cobotta_driver/GetBrakeStateResponse.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATERESPONSE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct GetBrakeStateResponse_
{
  typedef GetBrakeStateResponse_<ContainerAllocator> Type;

  GetBrakeStateResponse_()
    : state()
    , success(false)  {
    }
  GetBrakeStateResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _state_type;
  _state_type state;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetBrakeStateResponse_

typedef ::denso_cobotta_driver::GetBrakeStateResponse_<std::allocator<void> > GetBrakeStateResponse;

typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateResponse > GetBrakeStateResponsePtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::GetBrakeStateResponse const> GetBrakeStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aafd640535ae055e319908df5e1e05da";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaafd640535ae055eULL;
  static const uint64_t static_value2 = 0x319908df5e1e05daULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/GetBrakeStateResponse";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] state\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBrakeStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::GetBrakeStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.state[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATERESPONSE_H
