// Generated by gencpp from file denso_cobotta_driver/GetBrakeState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/GetBrakeStateRequest.h>
#include <denso_cobotta_driver/GetBrakeStateResponse.h>


namespace denso_cobotta_driver
{

struct GetBrakeState
{

typedef GetBrakeStateRequest Request;
typedef GetBrakeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBrakeState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::GetBrakeState > {
  static const char* value()
  {
    return "aafd640535ae055e319908df5e1e05da";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::GetBrakeState > {
  static const char* value()
  {
    return "denso_cobotta_driver/GetBrakeState";
  }

  static const char* value(const ::denso_cobotta_driver::GetBrakeState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::GetBrakeStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::GetBrakeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::GetBrakeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::GetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetBrakeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::GetBrakeStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::GetBrakeState >
template<>
struct DataType< ::denso_cobotta_driver::GetBrakeStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::GetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetBrakeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::GetBrakeStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::GetBrakeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::GetBrakeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::GetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetBrakeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::GetBrakeStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::GetBrakeState >
template<>
struct DataType< ::denso_cobotta_driver::GetBrakeStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::GetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetBrakeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_GETBRAKESTATE_H
