// Generated by gencpp from file denso_cobotta_driver/GetMotorState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/GetMotorStateRequest.h>
#include <denso_cobotta_driver/GetMotorStateResponse.h>


namespace denso_cobotta_driver
{

struct GetMotorState
{

typedef GetMotorStateRequest Request;
typedef GetMotorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotorState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::GetMotorState > {
  static const char* value()
  {
    return "271f2b21ec71f675bf49eb4b1873d850";
  }

  static const char* value(const ::denso_cobotta_driver::GetMotorState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::GetMotorState > {
  static const char* value()
  {
    return "denso_cobotta_driver/GetMotorState";
  }

  static const char* value(const ::denso_cobotta_driver::GetMotorState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::GetMotorStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::GetMotorState >
template<>
struct MD5Sum< ::denso_cobotta_driver::GetMotorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::GetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetMotorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::GetMotorStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::GetMotorState >
template<>
struct DataType< ::denso_cobotta_driver::GetMotorStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::GetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetMotorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::GetMotorStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::GetMotorState >
template<>
struct MD5Sum< ::denso_cobotta_driver::GetMotorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::GetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetMotorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::GetMotorStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::GetMotorState >
template<>
struct DataType< ::denso_cobotta_driver::GetMotorStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::GetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::GetMotorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATE_H
