// Generated by gencpp from file denso_cobotta_driver/GetMotorStateResponse.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATERESPONSE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct GetMotorStateResponse_
{
  typedef GetMotorStateResponse_<ContainerAllocator> Type;

  GetMotorStateResponse_()
    : state(false)
    , success(false)  {
    }
  GetMotorStateResponse_(const ContainerAllocator& _alloc)
    : state(false)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMotorStateResponse_

typedef ::denso_cobotta_driver::GetMotorStateResponse_<std::allocator<void> > GetMotorStateResponse;

typedef boost::shared_ptr< ::denso_cobotta_driver::GetMotorStateResponse > GetMotorStateResponsePtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::GetMotorStateResponse const> GetMotorStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "271f2b21ec71f675bf49eb4b1873d850";
  }

  static const char* value(const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x271f2b21ec71f675ULL;
  static const uint64_t static_value2 = 0xbf49eb4b1873d850ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/GetMotorStateResponse";
  }

  static const char* value(const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMotorStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::GetMotorStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_GETMOTORSTATERESPONSE_H
