// Generated by gencpp from file denso_cobotta_driver/SafeState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SAFESTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SAFESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct SafeState_
{
  typedef SafeState_<ContainerAllocator> Type;

  SafeState_()
    : state_code(0)
    , state_subcode(0)  {
    }
  SafeState_(const ContainerAllocator& _alloc)
    : state_code(0)
    , state_subcode(0)  {
  (void)_alloc;
    }



   typedef uint32_t _state_code_type;
  _state_code_type state_code;

   typedef uint32_t _state_subcode_type;
  _state_subcode_type state_subcode;





  typedef boost::shared_ptr< ::denso_cobotta_driver::SafeState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::SafeState_<ContainerAllocator> const> ConstPtr;

}; // struct SafeState_

typedef ::denso_cobotta_driver::SafeState_<std::allocator<void> > SafeState;

typedef boost::shared_ptr< ::denso_cobotta_driver::SafeState > SafeStatePtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::SafeState const> SafeStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::SafeState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::SafeState_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SafeState_<ContainerAllocator2> & rhs)
{
  return lhs.state_code == rhs.state_code &&
    lhs.state_subcode == rhs.state_subcode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::SafeState_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SafeState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SafeState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SafeState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SafeState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6778351a17e3634b544e31281fc203a";
  }

  static const char* value(const ::denso_cobotta_driver::SafeState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6778351a17e3634ULL;
  static const uint64_t static_value2 = 0xb544e31281fc203aULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/SafeState";
  }

  static const char* value(const ::denso_cobotta_driver::SafeState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 state_code\n"
"uint32 state_subcode\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::SafeState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_code);
      stream.next(m.state_subcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafeState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::SafeState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::SafeState_<ContainerAllocator>& v)
  {
    s << indent << "state_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state_code);
    s << indent << "state_subcode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state_subcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SAFESTATE_H
