// Generated by gencpp from file denso_cobotta_driver/SetBrakeState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/SetBrakeStateRequest.h>
#include <denso_cobotta_driver/SetBrakeStateResponse.h>


namespace denso_cobotta_driver
{

struct SetBrakeState
{

typedef SetBrakeStateRequest Request;
typedef SetBrakeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBrakeState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::SetBrakeState > {
  static const char* value()
  {
    return "ae7dda53a675ec4b8a49daeadb776d4c";
  }

  static const char* value(const ::denso_cobotta_driver::SetBrakeState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::SetBrakeState > {
  static const char* value()
  {
    return "denso_cobotta_driver/SetBrakeState";
  }

  static const char* value(const ::denso_cobotta_driver::SetBrakeState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::SetBrakeStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetBrakeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetBrakeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetBrakeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetBrakeStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::SetBrakeState >
template<>
struct DataType< ::denso_cobotta_driver::SetBrakeStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetBrakeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::SetBrakeStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetBrakeState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetBrakeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetBrakeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetBrakeStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::SetBrakeState >
template<>
struct DataType< ::denso_cobotta_driver::SetBrakeStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetBrakeState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetBrakeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATE_H
