// Generated by gencpp from file denso_cobotta_driver/SetBrakeStateRequest.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATEREQUEST_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct SetBrakeStateRequest_
{
  typedef SetBrakeStateRequest_<ContainerAllocator> Type;

  SetBrakeStateRequest_()
    : state()  {
    }
  SetBrakeStateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBrakeStateRequest_

typedef ::denso_cobotta_driver::SetBrakeStateRequest_<std::allocator<void> > SetBrakeStateRequest;

typedef boost::shared_ptr< ::denso_cobotta_driver::SetBrakeStateRequest > SetBrakeStateRequestPtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::SetBrakeStateRequest const> SetBrakeStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5958fa30c9a253a1f2857ed1c1f2b7f";
  }

  static const char* value(const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5958fa30c9a253aULL;
  static const uint64_t static_value2 = 0x1f2857ed1c1f2b7fULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/SetBrakeStateRequest";
  }

  static const char* value(const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] state\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBrakeStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::SetBrakeStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SETBRAKESTATEREQUEST_H
