// Generated by gencpp from file denso_cobotta_driver/SetLEDState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/SetLEDStateRequest.h>
#include <denso_cobotta_driver/SetLEDStateResponse.h>


namespace denso_cobotta_driver
{

struct SetLEDState
{

typedef SetLEDStateRequest Request;
typedef SetLEDStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::SetLEDState > {
  static const char* value()
  {
    return "2ae38ea1f2419ff3e6383563a0531fc9";
  }

  static const char* value(const ::denso_cobotta_driver::SetLEDState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::SetLEDState > {
  static const char* value()
  {
    return "denso_cobotta_driver/SetLEDState";
  }

  static const char* value(const ::denso_cobotta_driver::SetLEDState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::SetLEDStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetLEDState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetLEDStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetLEDState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetLEDStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetLEDStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::SetLEDState >
template<>
struct DataType< ::denso_cobotta_driver::SetLEDStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetLEDState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetLEDStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::SetLEDStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetLEDState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetLEDStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetLEDState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetLEDStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetLEDStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::SetLEDState >
template<>
struct DataType< ::denso_cobotta_driver::SetLEDStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetLEDState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetLEDStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATE_H
