// Generated by gencpp from file denso_cobotta_driver/SetLEDStateRequest.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATEREQUEST_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_driver
{
template <class ContainerAllocator>
struct SetLEDStateRequest_
{
  typedef SetLEDStateRequest_<ContainerAllocator> Type;

  SetLEDStateRequest_()
    : red(0)
    , green(0)
    , blue(0)
    , blink_rate(0)  {
    }
  SetLEDStateRequest_(const ContainerAllocator& _alloc)
    : red(0)
    , green(0)
    , blue(0)
    , blink_rate(0)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _green_type;
  _green_type green;

   typedef uint8_t _blue_type;
  _blue_type blue;

   typedef uint8_t _blink_rate_type;
  _blink_rate_type blink_rate;





  typedef boost::shared_ptr< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLEDStateRequest_

typedef ::denso_cobotta_driver::SetLEDStateRequest_<std::allocator<void> > SetLEDStateRequest;

typedef boost::shared_ptr< ::denso_cobotta_driver::SetLEDStateRequest > SetLEDStateRequestPtr;
typedef boost::shared_ptr< ::denso_cobotta_driver::SetLEDStateRequest const> SetLEDStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.red == rhs.red &&
    lhs.green == rhs.green &&
    lhs.blue == rhs.blue &&
    lhs.blink_rate == rhs.blink_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator1> & lhs, const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d795d035803e2fcf59d84d94026a549";
  }

  static const char* value(const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d795d035803e2fcULL;
  static const uint64_t static_value2 = 0xf59d84d94026a549ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_driver/SetLEDStateRequest";
  }

  static const char* value(const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 red\n"
"uint8 green\n"
"uint8 blue\n"
"uint8 blink_rate\n"
;
  }

  static const char* value(const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
      stream.next(m.blink_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLEDStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_driver::SetLEDStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
    s << indent << "blink_rate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blink_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SETLEDSTATEREQUEST_H
