// Generated by gencpp from file denso_cobotta_driver/SetMotorState.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_DRIVER_MESSAGE_SETMOTORSTATE_H
#define DENSO_COBOTTA_DRIVER_MESSAGE_SETMOTORSTATE_H

#include <ros/service_traits.h>


#include <denso_cobotta_driver/SetMotorStateRequest.h>
#include <denso_cobotta_driver/SetMotorStateResponse.h>


namespace denso_cobotta_driver
{

struct SetMotorState
{

typedef SetMotorStateRequest Request;
typedef SetMotorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorState
} // namespace denso_cobotta_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::denso_cobotta_driver::SetMotorState > {
  static const char* value()
  {
    return "4581db74aae4efc6534413a8b210908c";
  }

  static const char* value(const ::denso_cobotta_driver::SetMotorState&) { return value(); }
};

template<>
struct DataType< ::denso_cobotta_driver::SetMotorState > {
  static const char* value()
  {
    return "denso_cobotta_driver/SetMotorState";
  }

  static const char* value(const ::denso_cobotta_driver::SetMotorState&) { return value(); }
};


// service_traits::MD5Sum< ::denso_cobotta_driver::SetMotorStateRequest> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetMotorState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetMotorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetMotorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetMotorStateRequest> should match
// service_traits::DataType< ::denso_cobotta_driver::SetMotorState >
template<>
struct DataType< ::denso_cobotta_driver::SetMotorStateRequest>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetMotorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::denso_cobotta_driver::SetMotorStateResponse> should match
// service_traits::MD5Sum< ::denso_cobotta_driver::SetMotorState >
template<>
struct MD5Sum< ::denso_cobotta_driver::SetMotorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::denso_cobotta_driver::SetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetMotorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::denso_cobotta_driver::SetMotorStateResponse> should match
// service_traits::DataType< ::denso_cobotta_driver::SetMotorState >
template<>
struct DataType< ::denso_cobotta_driver::SetMotorStateResponse>
{
  static const char* value()
  {
    return DataType< ::denso_cobotta_driver::SetMotorState >::value();
  }
  static const char* value(const ::denso_cobotta_driver::SetMotorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DENSO_COBOTTA_DRIVER_MESSAGE_SETMOTORSTATE_H
