// Generated by gencpp from file denso_cobotta_gripper/GripperMoveFeedback.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEFEEDBACK_H
#define DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_gripper
{
template <class ContainerAllocator>
struct GripperMoveFeedback_
{
  typedef GripperMoveFeedback_<ContainerAllocator> Type;

  GripperMoveFeedback_()
    : position(0.0)
    , stalled(false)
    , reached_goal(false)  {
    }
  GripperMoveFeedback_(const ContainerAllocator& _alloc)
    : position(0.0)
    , stalled(false)
    , reached_goal(false)  {
  (void)_alloc;
    }



   typedef double _position_type;
  _position_type position;

   typedef uint8_t _stalled_type;
  _stalled_type stalled;

   typedef uint8_t _reached_goal_type;
  _reached_goal_type reached_goal;





  typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GripperMoveFeedback_

typedef ::denso_cobotta_gripper::GripperMoveFeedback_<std::allocator<void> > GripperMoveFeedback;

typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveFeedback > GripperMoveFeedbackPtr;
typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveFeedback const> GripperMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.stalled == rhs.stalled &&
    lhs.reached_goal == rhs.reached_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffc2fb41cfc90efec9eb5bd987b5cbf4";
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffc2fb41cfc90efeULL;
  static const uint64_t static_value2 = 0xc9eb5bd987b5cbf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_gripper/GripperMoveFeedback";
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 position  # The current gripper position (in meters)\n"
"bool stalled      # True iff the gripper is exerting max effort and not moving\n"
"bool reached_goal # True iff the gripper position has reached the commanded setpoint\n"
;
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.stalled);
      stream.next(m.reached_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_gripper::GripperMoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "stalled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stalled);
    s << indent << "reached_goal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEFEEDBACK_H
