// Generated by gencpp from file denso_cobotta_gripper/GripperMoveGoal.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEGOAL_H
#define DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_gripper
{
template <class ContainerAllocator>
struct GripperMoveGoal_
{
  typedef GripperMoveGoal_<ContainerAllocator> Type;

  GripperMoveGoal_()
    : target_position(0.0)
    , speed(0.0)
    , effort(0.0)  {
    }
  GripperMoveGoal_(const ContainerAllocator& _alloc)
    : target_position(0.0)
    , speed(0.0)
    , effort(0.0)  {
  (void)_alloc;
    }



   typedef double _target_position_type;
  _target_position_type target_position;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GripperMoveGoal_

typedef ::denso_cobotta_gripper::GripperMoveGoal_<std::allocator<void> > GripperMoveGoal;

typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveGoal > GripperMoveGoalPtr;
typedef boost::shared_ptr< ::denso_cobotta_gripper::GripperMoveGoal const> GripperMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_position == rhs.target_position &&
    lhs.speed == rhs.speed &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "991e9685b46a7195c4e7ad3c7b7809ce";
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x991e9685b46a7195ULL;
  static const uint64_t static_value2 = 0xc4e7ad3c7b7809ceULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_gripper/GripperMoveGoal";
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64  target_position\n"
"float32  speed\n"
"float32  effort\n"
;
  }

  static const char* value(const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position);
      stream.next(m.speed);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_gripper::GripperMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_position: ";
    Printer<double>::stream(s, indent + "  ", v.target_position);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "effort: ";
    Printer<float>::stream(s, indent + "  ", v.effort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_GRIPPER_MESSAGE_GRIPPERMOVEGOAL_H
