// Generated by gencpp from file denso_cobotta_gripper/VacuumMoveFeedback.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEFEEDBACK_H
#define DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_gripper
{
template <class ContainerAllocator>
struct VacuumMoveFeedback_
{
  typedef VacuumMoveFeedback_<ContainerAllocator> Type;

  VacuumMoveFeedback_()
    : pressure(0.0)
    , stalled(false)  {
    }
  VacuumMoveFeedback_(const ContainerAllocator& _alloc)
    : pressure(0.0)
    , stalled(false)  {
  (void)_alloc;
    }



   typedef double _pressure_type;
  _pressure_type pressure;

   typedef uint8_t _stalled_type;
  _stalled_type stalled;





  typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct VacuumMoveFeedback_

typedef ::denso_cobotta_gripper::VacuumMoveFeedback_<std::allocator<void> > VacuumMoveFeedback;

typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveFeedback > VacuumMoveFeedbackPtr;
typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveFeedback const> VacuumMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.pressure == rhs.pressure &&
    lhs.stalled == rhs.stalled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "794836023aebbbc75ac9fc72f83a8a28";
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x794836023aebbbc7ULL;
  static const uint64_t static_value2 = 0x5ac9fc72f83a8a28ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_gripper/VacuumMoveFeedback";
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 pressure  # Not implemented.\n"
"bool stalled      # True iff the gripper is exerting max effort and not moving\n"
"\n"
;
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
      stream.next(m.stalled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VacuumMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_gripper::VacuumMoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
    s << indent << "stalled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stalled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEFEEDBACK_H
