// Generated by gencpp from file denso_cobotta_gripper/VacuumMoveGoal.msg
// DO NOT EDIT!


#ifndef DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEGOAL_H
#define DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace denso_cobotta_gripper
{
template <class ContainerAllocator>
struct VacuumMoveGoal_
{
  typedef VacuumMoveGoal_<ContainerAllocator> Type;

  VacuumMoveGoal_()
    : direction(0)
    , power_percentage(0.0)  {
    }
  VacuumMoveGoal_(const ContainerAllocator& _alloc)
    : direction(0)
    , power_percentage(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _direction_type;
  _direction_type direction;

   typedef double _power_percentage_type;
  _power_percentage_type power_percentage;





  typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct VacuumMoveGoal_

typedef ::denso_cobotta_gripper::VacuumMoveGoal_<std::allocator<void> > VacuumMoveGoal;

typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveGoal > VacuumMoveGoalPtr;
typedef boost::shared_ptr< ::denso_cobotta_gripper::VacuumMoveGoal const> VacuumMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.power_percentage == rhs.power_percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator1> & lhs, const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_cobotta_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44fa814773c8fc7eca6878dd64e3fabc";
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44fa814773c8fc7eULL;
  static const uint64_t static_value2 = 0xca6878dd64e3fabcULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_cobotta_gripper/VacuumMoveGoal";
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 direction\n"
"float64 power_percentage\n"
;
  }

  static const char* value(const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.power_percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VacuumMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_cobotta_gripper::VacuumMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
    s << indent << "power_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.power_percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_COBOTTA_GRIPPER_MESSAGE_VACUUMMOVEGOAL_H
