controller_list:
  - name: arm_a_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_a_arm_joint_0
      - arm_a_arm_joint_1
      - arm_a_arm_joint_2
      - arm_a_arm_joint_3
      - arm_a_arm_joint_4
      - arm_a_arm_joint_5

  - name: arm_b_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_b_arm_joint_0
      - arm_b_arm_joint_1
      - arm_b_arm_joint_2
      - arm_b_arm_joint_3
      - arm_b_arm_joint_4
      - arm_b_arm_joint_5

initial:  # Define initial robot poses per group
  - group: arm_a
    pose: home_a

  - group: arm_b
    pose: home_b
