controller_list:
  - name: arm_a_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_a_arm_joint_0
      - arm_a_arm_joint_1
      - arm_a_arm_joint_2
      - arm_a_arm_joint_3
      - arm_a_arm_joint_4
      - arm_a_arm_joint_5

  - name: arm_b_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: False
    joints:
      - arm_b_arm_joint_0
      - arm_b_arm_joint_1
      - arm_b_arm_joint_2
      - arm_b_arm_joint_3
      - arm_b_arm_joint_4
      - arm_b_arm_joint_5
