controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: mycobot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - mycobot_arm_joint_0
      - mycobot_arm_joint_1
      - mycobot_arm_joint_2
      - mycobot_arm_joint_3
      - mycobot_arm_joint_4
      - mycobot_arm_joint_5