controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - mycobot_arm_joint_0
      - mycobot_arm_joint_1
      - mycobot_arm_joint_2
      - mycobot_arm_joint_3
      - mycobot_arm_joint_4
      - mycobot_arm_joint_5
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - cobotta_joint_1
      - cobotta_joint_2
      - cobotta_joint_3
      - cobotta_joint_4
      - cobotta_joint_5
      - cobotta_joint_6
initial:  # Define initial robot poses per group
#  - group: arm_group
#    pose: home

  []